language: java
os: linux
dist: trusty
jdk: oraclejdk13
script:
- "./gradlew jar"
- java -jar build/libs/http-server.jar &
- cd feature-tests
- bundle install
- bundle exec spinach
- cd ..
after_success:
- "./gradlew test jacocoTestReport"
- bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: UArCkB3r6qJDZvQpoV1IpUpgrW2IMCTVpMreBdHJYQuWCTFdqoMsgd7fzQbKV5UPeTzHHJjlOplo1VWt9YoHyaYkuWwcT3A6i6rFxsedEa5rp7jCkhLyruELYmyrnFFpQXKBtnBo02fxfz7ofT2EsYYA/3PkGWccDWeg0oLUEYlzIZ+LpGHtgo6QwMKTAKlGdW1BkQs3MOz8COm+ccvbLIcaZjvEQZg3H9lmSmfrM4SAFGBYX72hH9ymI5/VghTuRzXnZJFwKD8guv5tABnmL97A02oZVmptTzRD+ayLuBk/pnetyjGIhblDn96i/JrJbTTmDAR1aXbnrJHiLwm3YnP9Amta0Y9ywhTtUY6DGBD0K17/y5tncJD0HAdzhEmEf0DY8S5n5pR7j5sg1npSykfdAkdx8HclPCoNHKTaxrKkPA3p8wfluCjFnhE2nddLXRUdFSFk+7OYPtsdoWaC5CbnBH58DAYDZvJaj/LyVcQ+fn0L0U6XIR5cKo35D0yLv02jFdGaDYmvlILclPH+8AdDgKoroqM0VF1vSWmmgTl6hhxj7nrnhn6uAG1KhAXrcCPOJ3wR58xLggsvTCmfpaOg+wOYyVH7T5+G4Yp8TSlzN42LQO+a8P781yncfqSZgCtnYO8EZdzKtYWJZoLt7Fz/8meZRzf2shry5U0HDk4=
  app: sam-jones-http-server
  on:
    repo: samjones1001/http-server
    branch: master