language: java
os: linux
dist: trusty
jdk: oraclejdk13
script:
- "./gradlew jar"
- java -jar build/libs/http-server.jar &
- cd feature-tests
- bundle install
- bundle exec spinach
- cd ..
after_success:
- "./gradlew test jacocoTestReport"
- bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: sam-jones-http-server
  on:
    repo: samjones1001/http-server
    branch: master