coverage:
  status:
    project:
      default:
        target: 90
        threshold: 5
        base: parent
    patch:
      default:
        target: 80
        threshold: 5
        base: parent
ignore:
  - "src/main/java/http/server/controller"